== The Workshop Environment You Are Using

Your AWS environment has already been set up. It contains a pre-deployed ROSA cluster which has been configured with Amazon Cognito as the identity provider (idp) for OpenShift user management. 

Your workshop environment consists of several other cloud resources which have been pre-configured and are ready to use.
This includes a %aws_web_console_url%[Amazon Web Services (AWS)] account, and many other supporting resources.

ROSA is enabled on the AWS account used for this lab, and the ROSA CLI as well as AWS CLI tools are installed and configured on your bastion VM.

== Connect to your bastion VM

. In the terminal window to the right connect to the bastion VM (you can also just click the command below to have it copied and executed automatically):
+
[TIP]
====
Answer `yes` when asked if to accept the host key.

The password for the user %rosa_bastion_user_name% is `%rosa_user_password%`
====
+
[source,sh,role=execute]
----
ssh %rosa_bastion_user_name%@bastion.%rosa_subdomain_base%
----
+
.Click in the box below to copy and paste the string `yes` to your terminal:
+
[source,sh,role=execute]
----
yes
----
+
.Click in the box below to copy and paste the password to your terminal:
+
[source,sh,role=execute]
----
%rosa_user_password%
----

=== Validate installed tools

You will be using the `rosa`, `aws` and `oc` command line tools throughout this lab.

. Verify that the `rosa` command line tool is installed (note that your version may be a more recent version than the output shown below):
+
[source,sh,role=execute]
----
rosa version
----
+
.Sample Output
[source,texinfo]
----
1.2.26
Your ROSA CLI is up to date.
----

. Verify that the `aws` command line tool is installed:
+
[source,sh,role=execute]
----
aws --version
----
+
.Sample Output
[source,text,options=nowrap]
----
aws-cli/2.13.20 Python/3.11.5 Linux/5.14.0-284.30.1.el9_2.x86_64 exe/x86_64.rhel.9 prompt/off
----

. Verify that the `aws` command line tool is configured correctly:
+
[source,sh,role=execute]
----
aws sts get-caller-identity
----
+
.Sample Output
[source,texinfo]
----
{
    "UserId": "AIDA52VPS74UJLY4GUW7L",
    "Account": "950629760808",
    "Arn": "arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4"
}
----

. Verify that the `oc` CLI is installed correctly
+
[source,sh,role=execute]
----
rosa verify openshift-client
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Verifying whether OpenShift command-line tool is available...
I: Current OpenShift Client Version: 4.13.13
----

. Rosa login
+
[source,sh,role=execute]
----
rosa login
----
+
.Sample Output
[source,texinfo]
----
I: Logged in as 'rhpds-cloud' on 'https://api.openshift.com'
----
+
[NOTE]
====
Normally you would need to get a *token* from the https://console.redhat.com/openshift/token/rosa)[Red Hat Console] and log into ROSA using that token.

In this environment your token has been preconfigured for you.
====

. Run rosa whoami to verify your credentials:
+
[source,sh,role=execute]
----
rosa whoami
----
+
.Sample Output
[source,texinfo]
----
AWS ARN:                      arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4
AWS Account ID:               950629760808
AWS Default Region:           us-east-2
OCM API:                      https://api.openshift.com
OCM Account Email:            rhpds-admins+cloud@redhat.com
OCM Account ID:               1z8aXAxD3PWdlWiNRIE588rHD9l
OCM Account Name:             RHPDS Cloud
OCM Account Username:         rhpds-cloud
OCM Organization External ID: 15324659
OCM Organization ID:          1z8aXAQ73DYAPLeCZhNq1MRQ0ZL
OCM Organization Name:        Red Hat, Inc.
----


=== Using the ROSA Command Line

The ROSA command line utility provides tooling to view and interact with Red Hat OpenShift Service on AWS (ROSA). The ROSA CLI will allow administrators to perform some common tasks quickly.


. For example, using the ROSA CLI, you can verify that your AWS account has enough quota in the region you will be deploying your cluster to.
+
[source,sh,role=execute]
----
rosa verify quota
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Validating AWS quota...
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against https://docs.openshift.com/
rosa/rosa_getting_started/rosa-required-aws-service-quotas.html
----
+
. Let's use the ROSA CLI to view details about our ROSA deployment. First let's list the clusters we have
+
[source,sh,role=execute]
----
rosa verify quota
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
ID                                NAME        STATE  TOPOLOGY
2740pit37ia213l9iu7g8ha0rjtpujda  rosa-4mg7f  ready  Classic (STS)
----
+
See https://docs.openshift.com/rosa/rosa_planning/rosa-sts-required-aws-service-quotas.html[the documentation] for more details regarding quotas.
+
. Now we will collect the details to connect to the cluster. We will query the ROSA cluster to gather the Web console URL and the path of the API endpoint. We will also write these details to the .bashrc so they are loaded into our environment variables and easily accessed via the command line.
+
[source,sh,role=execute]
----
export API=$(rosa describe cluster -c rosa-${GUID} -o json | jq -r .api.url)
echo "export API=$(rosa describe cluster -c rosa-${GUID} -o json | jq -r .api.url)" >> ~/.bashrc


export CONSOLE_URL=$(rosa describe cluster -c rosa-${GUID} -o json | jq -r .console.url)
echo "export CONSOLE_URL=$(rosa describe cluster -c rosa-${GUID} -o json | jq -r .console.url)" >> ~/.bashrc

source ~/.bashrc

printf "ROSA API: $API\n\nROSA Web Console: $CONSOLE_URL"
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
ROSA API: https://api.rosa-4mg7f.m0rb.p1.openshiftapps.com:6443

ROSA Web Console: https://console-openshift-console.apps.rosa-4mg7f.m0rb.p1.openshiftapps.com
----
+

We have used the ROSA CLI to query our cluster. We are now ready to login to ROSA and deploy an application.
